- name: Install APT packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
   - "{{ apt_packages }}"
  tags: [common]

- name: Host is present
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ item.host_ip }}"
    line: "{{ item.host_ip }} {{ item.host_name }}"
  with_items: "{{ hosts }}"
  tags: [common]