- name: Create a new swarm
  shell: "docker swarm init --advertise-addr {{ swarm_master_addr }}"
  when: swarm_master|bool

- name: Register swarm token
  shell: "docker swarm join-token worker | awk '/--token/ {print $2}'"
  register: docker_swarm_token
  when: swarm_master|bool

- set_fact:
    docker_swarm_token_parsed: "{{ hostvars['10.10.10.101']['docker_swarm_token']['stdout'] }}"

- fail:
    msg: "Cannot load Docker Swarm Token"
  when: docker_swarm_token_parsed == ""

- debug: var=docker_swarm_token_parsed

- name: Leave old swarm
  shell: "docker swarm leave --force"
  when: swarm_master == false
  ignore_errors: yes

- name: Join a new swarm
  shell: "docker swarm join --token {{ docker_swarm_token_parsed }} {{ swarm_master_addr }}"
  when: swarm_master == false
  ignore_errors: yes